### ISSUE TITLE
isNoDisplay.m

### ISSUE THREAD

**Issue by kfchou** [mim/messl#3]
It seems like the repo is missing a a isNoDisplay.m function. It's called in the subplots() function, line 15.

**Comment by mim** [comment]
The isNoDisplay.m function is in the repo: https://github.com/mim/messl/blob/master/isNoDisplay.m .  Could you check that you've got the latest version of the whole repo and if it's still a problem, post the exact error you're getting?

**Comment by kfchou** [comment]
ah, sorry. The missing file or function is 'reMatch'

```
Undefined function or variable 'reMatch'.

Error in isNoDisplay (line 7)
if ~reMatch(d, ':\d+')

```

**Comment by mim** [comment]
You can find it in my [mimLib repository](http://github.com/mim/mimLib), but I've added it as a sub-function to `isNoDisplay` in a7e9e43456c03381256be85815620241a346d3f9 , so as of that change it should be self-contained here.
