### ISSUE TITLE
LogProbGmm

### ISSUE THREAD

**Issue by FAZLIHADI** [mim/messl#4]
I am trying to run the code but it give me error "Undefined function 'logProbGmm' for input arguments of type 'single'". help me how to fix this.
Undefined function 'logProbGmm' for input arguments of type 'single'.

Error in messl>computeIpdLogLikelihood (line 335)
lpBin = single(logProbGmm(Erep, ipdParams.xi_wit, ...

Error in messl (line 176)
    lpIpd = computeIpdLogLikelihood(W,T,I,Nt,C,rep,Nrep, ipdParams, angE);

Error in Main (line 68)
[m,p] = messl(lr, tau, 2, 'vis', 1);

**Comment by mim** [comment]
I have included many pre-compiled mex versions of that function, but it looks like your system isn't one of them.  Please compile [`logProbGmm.cpp`](https://github.com/mim/messl/blob/master/logProbGmm.cpp) yourself using the `mex` command in matlab.
