### ISSUE TITLE
Issue with tdoa

### ISSUE THREAD

**Issue by akhilvasvani** [mim/messl#5]
Hi, 

I am running your example code you provided on your readME, and I cannot run the second part:

tdoa = phatLoc(lr, tau, 2, 1024, 1);
[m,p] = messl(ls, tau, 2, 'vis', 1, 'tauPosInit', tdoa);

I have ready defined lr, tau from your previous example code section, so those two variables are in order. However, when I run the messl function, I receive the error: "Index in position 1 exceeds array bounds (must not exceed 1)."

I do not think you did anything incorrect. More so, I might be missing a snippet of important code that I might've overlooked or you did not put up. Do you receive the same error? If not, what am I doing incorrectly?

Thanks.

**Comment by mim** [comment]
It looks like you have a typo in your call to `messl`: you are passing in the output of the `ls` function and not the signal `lr`.
